#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TrensCidades.Resource", IsApplication=true)]

namespace TrensCidades
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040009
			public const int btnAdicionarCaminho = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int btnAdicionarCidade = 2130968584;
			
			// aapt resource value: 0x7f040004
			public const int btnBuscar = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int layoutCanvas = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int spDeOnde = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int spParaOnde = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int tbCaminhos = 2130968583;
			
			// aapt resource value: 0x7f040001
			public const int tvDe = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int tvPara = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int tvResultados = 2130968582;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int item_spinner = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Main = 2130837505;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
